### ISSUE TITLE
A gif in readme would be great

### ISSUE THREAD

**Issue by kaunteya** [GitHawkApp/DropdownTitleView#1]

**Comment by heumn** [comment]
Hint @kaunteya ;)

![skjermbilde 2018-10-26 kl 13 29 13](https://user-images.githubusercontent.com/1769314/47563768-26a17b80-d923-11e8-81a3-53b0d0d1128c.png)

**Comment by heumn** [comment]
You can find it right over here: https://github.com/GitHawkApp/DropdownTitleView/pulls

**Comment by rnystrom** [comment]
Not sure what we would gif. There aren't any animations or anything!

**Comment by kaunteya** [comment]
@rnystrom Dropdown
